platform :osx, '10.8'
link_with 'GDChannel', 'GDChannelTests'

# pod 'J2ObjC', :path => '~/dev/tools/lib/j2objc/J2ObjC.podspec'
pod 'J2ObjC', :git => 'https://github.com/goodow/j2objc.git', :commit => '32284814b6352a8d8458d1b866c59f830a2dce42'
pod 'GDJson', :git => 'https://github.com/goodow/GDJson.git'

pod 'GDChannel', :path => '..'